[package]
name = "zshctl-daemon"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
fs2.workspace = true
fancy-regex.workspace = true
zshctl-config = { path = "../zshctl-config" }
zshctl-core = { path = "../zshctl-core" }
zshctl-history = { path = "../zshctl-history" }
zshctl-protocol = { path = "../zshctl-protocol" }
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
shell-words.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
