[package]
name = "zshctl-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "zshctl"
path = "src/main.rs"

[[bin]]
name = "zshctld"
path = "src/zshctld.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
zshctl-daemon = { path = "../zshctl-daemon" }
zshctl-protocol = { path = "../zshctl-protocol" }
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
